services:
  db:
    image: postgres:latest
    restart: unless-stopped
    user: postgres
    secrets:
      - readonly-password
      - dev-password
      - shell-user-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=/run/secrets/dev-password
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/postgres-data

secrets:
  readonly-password:
    file: db/readonly-password.txt
  dev-password:
    file: db/dev-password.txt
  shell-user-password:
    file: scripts/shell-user-password.txt